import React from "react";
import { DataSourceKind } from "../../types/common";

interface Props {
  kind: DataSourceKind;
  pill?: boolean;
}

export default function DataSourceBadge({ kind, pill = false }: Props) {
  if (kind === "DEMO") {
    if (pill) return <Pill color="#FFB000" label="DEMO" />;
    return <Banner color="#FFB000" label="DEMO ADAPTER" desc="Synthetic frontend behaviour. Not connected to the official Generals environment." />;
  }

  if (kind === "IMPORTED_PROJECT_EVIDENCE") {
    if (pill) return <Pill color="#22D3EE" label="IMPORTED" />;
    return <Banner color="#22D3EE" label="IMPORTED PROJECT EVIDENCE" desc="Real project record — immutable." />;
  }

  if (kind === "OFFICIAL_PORTAL_OBSERVATION") {
    if (pill) return <Pill color="#34D399" label="PORTAL OBS" />;
    return <Banner color="#34D399" label="OFFICIAL PORTAL OBSERVATION" desc="Observation copied from the competition portal. Not generated by the local evaluator." />;
  }

  if (kind === "MANUALLY_RECORDED") {
    if (pill) return <Pill color="#8593A1" label="MANUAL" />;
    return <Banner color="#8593A1" label="MANUALLY RECORDED" desc="Operator-entered record. Verify against the referenced package or portal observation." />;
  }

  return null;
}

function Pill({ color, label }: { color: string; label: string }) {
  return (
    <span
      className="inline-flex items-center px-1.5 py-0.5 rounded-sm border uppercase"
      style={{ fontFamily: "var(--font-mono)", fontSize: 9, letterSpacing: "0.08em", color, borderColor: `${color}66` }}
    >
      {label}
    </span>
  );
}

function Banner({ color, label, desc }: { color: string; label: string; desc: string }) {
  return (
    <div
      className="flex items-start gap-2 rounded-sm px-3 py-2 mb-4"
      style={{ border: `1px solid ${color}66`, backgroundColor: "#0C1116" }}
    >
      <span className="font-bold uppercase tracking-wider flex-shrink-0" style={{ fontFamily: "var(--font-mono)", fontSize: 10, color }}>
        {label}
      </span>
      <span className="text-[#8593A1]" style={{ fontFamily: "var(--font-mono)", fontSize: 10 }}>
        — {desc}
      </span>
    </div>
  );
}
