import React, { useState } from "react";
import { DataSourceKind } from "../../types/common";

interface Props {
  kind: DataSourceKind;
  pill?: boolean;
  recordedAt?: string | null;
  sourceManifest?: string | null;
  historical?: boolean;
}

const DISPLAY: Record<
  DataSourceKind,
  { pill: string; label: string; desc: string; color: string }
> = {
  DEMO: {
    pill: "DEMO",
    label: "Demo data",
    desc: "Synthetic frontend behaviour. Not connected to the official Generals environment.",
    color: "#FFB000",
  },
  IMPORTED_PROJECT_EVIDENCE: {
    pill: "RECORDED",
    label: "Recorded research result",
    desc: "Immutable evidence imported from a versioned project record. Internal kind: IMPORTED_PROJECT_EVIDENCE.",
    color: "#22D3EE",
  },
  OFFICIAL_PORTAL_OBSERVATION: {
    pill: "PORTAL",
    label: "Portal snapshot",
    desc: "Observation copied from the competition portal. Not generated by the local evaluator.",
    color: "#34D399",
  },
  MANUALLY_RECORDED: {
    pill: "MANUAL",
    label: "Manual record",
    desc: "Operator-entered record. Verify against the referenced package or portal observation.",
    color: "#8593A1",
  },
  LIVE_LOCAL_STATE: {
    pill: "LIVE",
    label: "Live local state",
    desc: "Current local repository or session state. May change as work progresses.",
    color: "#A78BFA",
  },
};

export default function DataSourceBadge({
  kind,
  pill = false,
  recordedAt,
  sourceManifest,
  historical,
}: Props) {
  const meta = DISPLAY[kind];
  if (!meta) return null;
  if (pill) return <Pill color={meta.color} label={meta.pill} title={meta.label} />;
  return (
    <ExpandableBanner
      color={meta.color}
      label={meta.label}
      desc={meta.desc}
      recordedAt={recordedAt}
      sourceManifest={sourceManifest}
      historical={historical}
      internalKind={kind}
    />
  );
}

function Pill({ color, label, title }: { color: string; label: string; title: string }) {
  return (
    <span
      title={title}
      className="inline-flex items-center px-1.5 py-0.5 rounded-sm border uppercase"
      style={{ fontFamily: "var(--font-mono)", fontSize: 9, letterSpacing: "0.08em", color, borderColor: `${color}66` }}
    >
      {label}
    </span>
  );
}

function ExpandableBanner({
  color,
  label,
  desc,
  recordedAt,
  sourceManifest,
  historical,
  internalKind,
}: {
  color: string;
  label: string;
  desc: string;
  recordedAt?: string | null;
  sourceManifest?: string | null;
  historical?: boolean;
  internalKind: string;
}) {
  const [open, setOpen] = useState(false);
  return (
    <div className="mb-4">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="w-full text-left flex items-start gap-2 rounded-sm px-3 py-2"
        style={{ border: `1px solid ${color}66`, backgroundColor: "#0C1116" }}
      >
        <span className="font-bold tracking-wider flex-shrink-0" style={{ fontFamily: "var(--font-mono)", fontSize: 10, color }}>
          {label}
        </span>
        <span className="text-[#8593A1]" style={{ fontFamily: "var(--font-mono)", fontSize: 10 }}>
          — {desc}
        </span>
      </button>
      {open && (
        <div className="mt-1 rounded-sm border border-[#1E2630] bg-[#0C1116] px-3 py-2 text-[#8593A1]" style={{ fontFamily: "var(--font-mono)", fontSize: 10 }}>
          <div>Immutable: {internalKind === "DEMO" || internalKind === "LIVE_LOCAL_STATE" ? "no" : "yes (recorded evidence)"}</div>
          <div>Perspective: {historical ? "historical" : "current"}</div>
          <div>Recorded at: {recordedAt || "NOT RECORDED"}</div>
          <div>Source: {sourceManifest || "NOT RECORDED"}</div>
          <div>Internal kind: {internalKind}</div>
          <div>
            <a className="text-[#22D3EE] hover:underline" href="/documentation/glossary">
              Glossary
            </a>
          </div>
        </div>
      )}
    </div>
  );
}
