"""Fixed geometry and action-space constants."""

from __future__ import annotations

MAX_HW = 21
PATCH = 3
PATCH_GRID = MAX_HW // PATCH  # 7
NUM_PATCHES = PATCH_GRID * PATCH_GRID  # 49
NUM_DIRECTIONS = 4
NUM_SPLITS = 2
MOVES_PER_CELL = NUM_DIRECTIONS * NUM_SPLITS  # 8
ACTIONS_PER_CELL = MOVES_PER_CELL + 1  # + BUILD
PASS_INDEX = 0
ACTION_DIM = 1 + ACTIONS_PER_CELL * MAX_HW * MAX_HW  # 3970
EMB_DIM = 192
N_HEADS = 4
N_LAYERS = 4
HL_GAUSS_BINS = 128
HL_GAUSS_MIN = -1.0
HL_GAUSS_MAX = 1.0
HL_GAUSS_SIGMA = 0.04
EMA_TAU = 0.999
DEATHTOUCH_TURN = 800
DRAW_TURN = 1200
